In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
games=pd.read_csv("data/games.csv")
content=pd.read_json("data/games_metadata.json",lines=True)

In [3]:
games.head()

app_id                              title date_release   win    mac  linux  \
0   13500  Prince of Persia: Warrior Within™   2008-11-21  True  False  False   
1   22364            BRINK: Agents of Change   2011-08-03  True  False  False   
2  113020       Monaco: What's Yours Is Mine   2013-04-24  True   True   True   
3  226560                 Escape Dead Island   2014-11-18  True  False  False   
4  249050            Dungeon of the ENDLESS™   2014-10-27  True   True  False   

          rating  positive_ratio  user_reviews  price_final  price_original  \
0  Very Positive              84          2199         9.99            9.99   
1       Positive              85            21         2.99            2.99   
2  Very Positive              92          3722        14.99           14.99   
3          Mixed              61           873        14.99           14.99   
4  Very Positive              88          8784        11.99           11.99   

   discount  steam_deck  
0       0.0        True  
1       0.0        True  
2       0.0        True  
3       0.0        True  
4       0.0        True

In [4]:
test=games[games["win"]==False]
test

app_id                                              title  \
30      458790      The House in Fata Morgana Original Soundtrack   
109     610070                            Rain World - Soundtrack   
180     453400             Squad - Original Soundtrack Vol. 1 & 2   
204     613230  Planescape: Torment: Enhanced Edition Official...   
214    2277010                               Postmouse Soundtrack   
...        ...                                                ...   
50626   947910                GLAD VALAKAS SIMULATOR - Soundtrack   
50628  1782140                   Yupitergrad 🚀: Sneaki Soundtrack   
50655  1126650                          The Forgotten: Soundtrack   
50677   945690                               CardLife: Soundtrack   
50692   921640                 Demon King Domination - Soundtrack   

      date_release    win    mac  linux           rating  positive_ratio  \
30      2016-05-13  False  False  False         Positive             100   
109     2017-03-27  False  False  False         Positive              80   
180     2016-04-29  False  False  False    Very Positive              93   
204     2017-04-11  False  False  False  Mostly Positive              70   
214     2023-01-30  False  False  False         Positive             100   
...            ...    ...    ...    ...              ...             ...   
50626   2018-09-21  False  False  False         Positive              92   
50628   2021-10-29  False  False  False         Positive             100   
50655   2021-03-13  False  False  False         Positive              90   
50677   2018-10-09  False  False  False  Mostly Positive              70   
50692   2019-05-08  False  False  False         Positive              88   

       user_reviews  price_final  price_original  discount  steam_deck  
30               32        11.99           11.99       0.0        True  
109              30         9.99            9.99       0.0        True  
180              97         6.99            6.99       0.0        True  
204              17         9.99            9.99       0.0        True  
214              27         0.00            0.00       0.0        True  
...             ...          ...             ...       ...         ...  
50626            13         0.00            0.00       0.0        True  
50628            12         0.00            0.00       0.0        True  
50655            10         0.00            0.00       0.0        True  
50677            10         0.00            0.00       0.0        True  
50692            17         0.00            0.00       0.0        True  

[796 rows x 13 columns]

In [5]:
games=games[:10000]

In [6]:
games=games[["app_id","title"]]

In [7]:
games=games.merge(content,on="app_id")


In [8]:
print(games.shape)
games.head()

(10000, 4)


app_id                              title  \
0   13500  Prince of Persia: Warrior Within™   
1   22364            BRINK: Agents of Change   
2  113020       Monaco: What's Yours Is Mine   
3  226560                 Escape Dead Island   
4  249050            Dungeon of the ENDLESS™   

                                         description  \
0  Enter the dark underworld of Prince of Persia ...   
1                                                      
2  Monaco: What's Yours Is Mine is a single playe...   
3  Escape Dead Island is a Survival-Mystery adven...   
4  Dungeon of the Endless is a Rogue-Like Dungeon...   

                                                tags  
0  [Action, Adventure, Parkour, Third Person, Gre...  
1                                           [Action]  
2  [Co-op, Stealth, Indie, Heist, Local Co-Op, St...  
3  [Zombies, Adventure, Survival, Action, Third P...  
4  [Roguelike, Strategy, Tower Defense, Pixel Gra...

In [9]:
games["description"]=games["description"].apply(lambda x:x.split())

In [10]:
games.head()

app_id                              title  \
0   13500  Prince of Persia: Warrior Within™   
1   22364            BRINK: Agents of Change   
2  113020       Monaco: What's Yours Is Mine   
3  226560                 Escape Dead Island   
4  249050            Dungeon of the ENDLESS™   

                                         description  \
0  [Enter, the, dark, underworld, of, Prince, of,...   
1                                                 []   
2  [Monaco:, What's, Yours, Is, Mine, is, a, sing...   
3  [Escape, Dead, Island, is, a, Survival-Mystery...   
4  [Dungeon, of, the, Endless, is, a, Rogue-Like,...   

                                                tags  
0  [Action, Adventure, Parkour, Third Person, Gre...  
1                                           [Action]  
2  [Co-op, Stealth, Indie, Heist, Local Co-Op, St...  
3  [Zombies, Adventure, Survival, Action, Third P...  
4  [Roguelike, Strategy, Tower Defense, Pixel Gra...

Cosine similarity for tags

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

In [11]:
count={}
for game_tag in games["tags"]:
    for tag in game_tag:
        if tag not in count:
            count[tag]=0
        else:
            count[tag]+=1
print(count)


{'Action': 4385, 'Adventure': 3961, 'Parkour': 88, 'Third Person': 647, 'Great Soundtrack': 1134, 'Singleplayer': 4891, 'Platformer': 717, 'Time Travel': 56, 'Atmospheric': 1838, 'Classic': 417, 'Hack and Slash': 327, 'Time Manipulation': 51, 'Gore': 679, 'Fantasy': 1213, 'Story Rich': 1785, 'Dark': 469, 'Open World': 815, 'Controller': 605, 'Dark Fantasy': 277, 'Puzzle': 1498, 'Co-op': 800, 'Stealth': 234, 'Indie': 4969, 'Heist': 36, 'Local Co-Op': 373, 'Strategy': 2346, 'Online Co-Op': 414, 'Top-Down': 513, 'Multiplayer': 1481, 'Crime': 106, 'Casual': 3124, 'Pixel Graphics': 1250, 'Local Multiplayer': 425, '2D': 2427, 'Loot': 118, 'Zombies': 221, 'Survival': 567, 'Horror': 914, 'Cartoony': 420, 'Survival Horror': 316, 'Third-Person Shooter': 172, 'Anime': 1340, 'Roguelike': 456, 'Tower Defense': 157, 'RPG': 2270, 'Sci-fi': 914, 'Dungeon Crawler': 302, 'Perma Death': 180, 'Procedural Generation': 366, 'Resource Management': 349, 'Difficult': 864, 'Roguelite': 435, 'Replay Value': 424,

In [13]:
all_tags=list(set(tag for game_tag in games['tags'] for tag in game_tag if count[tag]>=0))
print(len(all_tags))

437


In [14]:

def create_tag_vector(tags, all_tags):  
    vector = [0] * len(all_tags)
    for tag in tags:  
        if tag in all_tags:
            vector[all_tags.index(tag)] = 1
    return vector
tag_vectors=[]
for game_tag in games['tags']:
    tag_vectors.append(create_tag_vector(game_tag,all_tags))
game_tags_vec=pd.DataFrame(data=tag_vectors,columns=all_tags)

In [15]:
game_tags_vec.head()

Character Customization  Crowdfunded  Linear  Offroad  Wargame  3D  \
0                        0            0       0        0        0   0   
1                        0            0       0        0        0   0   
2                        0            0       0        0        0   0   
3                        0            0       0        0        0   0   
4                        0            0       0        0        0   0   

   Programming  Dark Comedy  Twin Stick Shooter  RPG  ...  Medieval  Surreal  \
0            0            0                   0    0  ...         0        0   
1            0            0                   0    0  ...         0        0   
2            0            0                   0    0  ...         0        0   
3            0            0                   0    0  ...         0        0   
4            0            0                   0    1  ...         0        0   

   3D Platformer  Real-Time with Pause  8-bit Music  Assassin  Pixel Graphics  \
0              0                     0            0         0               0   
1              0                     0            0         0               0   
2              0                     0            0         0               1   
3              0                     0            0         0               0   
4              0                     0            0         0               1   

   Volleyball  Replay Value  Funny  
0           0             0      0  
1           0             0      0  
2           0             0      0  
3           0             0      0  
4           0             1      0  

[5 rows x 437 columns]

In [16]:
tag_sim=cosine_similarity(game_tags_vec,game_tags_vec)

In [17]:
import pickle as pkl
pkl.dump(tag_sim,open("pkl_files/10000_tag_sim.pkl","wb"))

In [14]:
def recommend(game,sim):
    index=games[games["title"]==game].index[0]
    top_rec=sorted(list(enumerate(sim[index])),key=lambda x:x[1],reverse=True)
    for candidate in top_rec[1:11]:
        print(games.iloc[candidate[0]].title)

In [12]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
print(lemmatizer.lemmatize("criteria",pos="v"))

criteria


In [13]:
def lemmatize(text):
    y=[]
    for w in text.split():
        new_w=lemmatizer.lemmatize(w)
        y.append(new_w)
    return " ".join(y)

In [14]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [15]:
def stem(text):
    y=[]
    for w in text:
        new_w=ps.stem(w)
        y.append(new_w)
    return " ".join(y)

In [16]:
print(stem("abilities"))#?????wtf

a b i l i t i e s


In [17]:
games["description"]=games["description"].apply(stem)

In [18]:
games.head()

app_id                              title  \
0   13500  Prince of Persia: Warrior Within™   
1   22364            BRINK: Agents of Change   
2  113020       Monaco: What's Yours Is Mine   
3  226560                 Escape Dead Island   
4  249050            Dungeon of the ENDLESS™   

                                         description  \
0  enter the dark underworld of princ of persia w...   
1                                                      
2  monaco: what' your is mine is a singl player o...   
3  escap dead island is a survival-mysteri advent...   
4  dungeon of the endless is a rogue-lik dungeon-...   

                                                tags  
0  [Action, Adventure, Parkour, Third Person, Gre...  
1                                           [Action]  
2  [Co-op, Stealth, Indie, Heist, Local Co-Op, St...  
3  [Zombies, Adventure, Survival, Action, Third P...  
4  [Roguelike, Strategy, Tower Defense, Pixel Gra...

In [22]:
games.loc[4,"description"]

'dungeon of the endless is a rogue-lik dungeon-defens game, in which the player and their team of hero must protect the gener of their crash ship while explor an ever-expand dungeon, all while face wave of monster and special event as they tri to find their way out...'

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer as tfidf

In [21]:
tf_idf=tfidf(stop_words="english",max_features=400)
vector=tf_idf.fit_transform(games["description"]).toarray()
print(vector)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
tf_idf.get_feature_names_out()

In [34]:
des_sim=cosine_similarity(vector)

In [35]:
print(des_sim.shape)
des_sim

(2000, 2000)


array([[1.        , 0.        , 0.        , ..., 0.05001355, 0.        ,
        0.04762045],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.02401012, 0.        ,
        0.        ],
       ...,
       [0.05001355, 0.        , 0.02401012, ..., 1.        , 0.06748228,
        0.0470352 ],
       [0.        , 0.        , 0.        , ..., 0.06748228, 1.        ,
        0.12325895],
       [0.04762045, 0.        , 0.        , ..., 0.0470352 , 0.12325895,
        1.        ]])

In [41]:
game_name="Ace of Seafood"
print(games[games["title"]==game_name].description)
print('Based on description:\n')
recommend(game_name,des_sim)
print('Based on tag:\n')
recommend(game_name,tag_sim)

96    in the sea of the distant future, human have a...
Name: description, dtype: object
Based on description:

Guilty Gear X2 #Reload
Prime of Flames
Lords Of The Fallen™ 2014
Rise of the Third Power
CountryBalls Heroes
Fabulous - Angela's High School Reunion
Homefront®: The Revolution
NEO AQUARIUM - The King of Crustaceans -
Extremely Realistic Siege Warfare Simulator
Mars Horizon
Based on tag:

NEO AQUARIUM - The King of Crustaceans -
CRSED: F.O.A.D.
Just Cause
MDK2 HD
MDK
Goat Simulator: Waste of Space
Armed and Dangerous®
LEGO® Harry Potter: Years 1-4
Tom Clancy's Ghost Recon: Future Soldier™
Ultimate Epic Battle Simulator
